Repository NVIDIA/DALI, pull requests merged in 2023-03, with the labels that each got.

#4668 Add CPU-only and variable batch tests for conditionals
  dali/test/python/test_dali_cpu_only.py
  dali/test/python/test_dali_variable_batch_size.py
  dali/test/python/test_utils.py
Labels: conditional execution

#4689 Add simple sanity test for DALI Conditionals in tf.function
  dali/test/python/test_dali_tf_conditionals.py
  qa/TL0_tensorflow_plugin/test.sh
Labels: conditional execution

#4694 [AA] Add auto augmentation wrapper
  dali/python/nvidia/dali/auto_aug/__init__.py
  dali/python/nvidia/dali/auto_aug/core/__init__.py
  dali/python/nvidia/dali/auto_aug/core/_args.py
  dali/python/nvidia/dali/auto_aug/core/_augmentation.py
  dali/python/nvidia/dali/auto_aug/core/decorator.py
  dali/test/python/auto_aug/test_augmentation_decorator.py
  qa/TL0_python-self-test-core/test_body.sh
Labels: automatic augmentations

#4699 Add augmentations used by AA
  dali/python/nvidia/dali/auto_aug/augmentations.py
  dali/test/python/auto_aug/test_augmentations.py
Labels: automatic augmentations

#4696 [AA] Add select operator/wrapper
  dali/python/nvidia/dali/_autograph/impl/api.py
  dali/python/nvidia/dali/_conditionals.py
  dali/python/nvidia/dali/auto_aug/core/__init__.py
  dali/python/nvidia/dali/auto_aug/core/_select.py
  dali/test/python/auto_aug/test_select.py
Labels: conditional execution, automatic augmentations

#4702 Add AutoAugment and ImageNet policy
  dali/python/nvidia/dali/auto_aug/augmentations.py
  dali/python/nvidia/dali/auto_aug/auto_augment.py
  dali/python/nvidia/dali/auto_aug/core/__init__.py
  dali/python/nvidia/dali/auto_aug/core/_augmentation.py
  dali/python/nvidia/dali/auto_aug/core/_utils.py
  dali/python/nvidia/dali/auto_aug/core/policy.py
  dali/test/python/auto_aug/test_auto_augment.py
Labels: conditional execution, automatic augmentations

#4704 Add RandAugment and TrivialAugment to auto_aug module
  dali/python/nvidia/dali/auto_aug/auto_augment.py
  dali/python/nvidia/dali/auto_aug/core/decorator.py
  dali/python/nvidia/dali/auto_aug/core/policy.py
  dali/python/nvidia/dali/auto_aug/rand_augment.py
  dali/python/nvidia/dali/auto_aug/trivial_augment.py
  dali/test/python/auto_aug/test_rand_augment.py
  dali/test/python/auto_aug/test_trivial_augment.py
Labels: conditional execution, automatic augmentations

#4678 Add EfficientNet example using automatic augmentations with DALI
  docs/examples/use_cases/index.py
  docs/examples/use_cases/pytorch/efficientnet/Dockerfile
  docs/examples/use_cases/pytorch/efficientnet/LICENSE
  docs/examples/use_cases/pytorch/efficientnet/LOC_synset_mapping.json
  docs/examples/use_cases/pytorch/efficientnet/checkpoint2model.py
  docs/examples/use_cases/pytorch/efficientnet/classify.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/__init__.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/autoaugment.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/dali.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/dataloaders.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/gpu_affinity.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/logger.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/mixup.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/models/__init__.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/models/common.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/models/efficientnet.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/models/entrypoints.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/models/model.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/optimizers.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/quantization.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/smoothing.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/training.py
  docs/examples/use_cases/pytorch/efficientnet/image_classification/utils.py
  docs/examples/use_cases/pytorch/efficientnet/main.py
  docs/examples/use_cases/pytorch/efficientnet/multiproc.py
  docs/examples/use_cases/pytorch/efficientnet/readme.rst
  docs/examples/use_cases/pytorch/efficientnet/requirements.txt
  qa/TL3_EfficientNet_benchmark/test_pytorch.sh
Labels: automatic augmentations

#4697 Reduce memory footprint of conditional execution
  dali/pipeline/executor/executor.cc
  dali/pipeline/executor/executor.h
  dali/pipeline/executor/executor_test.cc
Labels: conditional execution

#4746 Fix bug in Arithmetic unary op implementation
  dali/operators/math/expressions/expression_impl_gpu_unary.cuh
  dali/test/python/operator_1/test_arithmetic_ops.py
Labels: important-fix
